### ISSUE TITLE
1.0.2 is stable now :)

### ISSUE THREAD

**Issue by splitice** [PeterMosmans/openssl#4]
1.0.2 is stable now :)

Any chance you could merge with OpenSSL_1_0_2-stable ?

**Comment by centminmod** [comment]
+1 for that

waves at @splitice

**Comment by drwetter** [comment]
joining the crowd with +1 :-)

**Comment by v998** [comment]
:+1:  :)

**Comment by PeterMosmans** [comment]
Hi @splitice , @centminmod , @drwetter , @v998 

Thanks for the posts, good to see that the fork is actually *useful*  :)
I'm already working on the merges, but due to the giant source code reformat these merges are long and plentiful. As there are plenty of opportunities for bugs to creep in I'd like to handle the merges with care, which takes time.

Please hang on, and the end result will be near soon (I expect this week).

Cheers,


Peter

**Comment by splitice** [comment]
@PeterMosmans Awesome.

I am well aware of complexities of what you are doing. Its the main reason I am leaving it to an expert like yourself :)

Take your time. I am happy to help test when you are done.

**Comment by PeterMosmans** [comment]
Please note that I'm still working on it but it is a *lot* (and I do mean a *lot* of work). Personally I don't see the advantages (yet) of this huge source code reformat. If it was refactoring, bugfixing or enhancements - yes. But changing whitespaces and brackets around, thereby increasing the chance of errors...
Let's hope this improves the future and maintainability if the OpenSSL codebase.

I'll keep you updated.

**Comment by centminmod** [comment]
Thanks @PeterMosmans much appreciated :)

**Comment by PeterMosmans** [comment]
Hurrah! A few days (and a lot of merging and testing) later it's here! Please find the latest working build at https://github.com/PeterMosmans/openssl/commit/56fc479407ed6291de82130aa425601f4fc99f02
This build passes all tests, but as always with OpenSSL I'm not convinced that the tests cover everything. It should be as least as bugfree as the original :)

Enjoy!

**Comment by drwetter** [comment]
Thx a lot, Peter! Compiled it for Linux (https://github.com/drwetter/testssl.sh/tree/master/openssl-bins/openssl-1.0.2-chacha.pm). 4 more ciphers also.
